package constants

const (
	ENV_DEBUG_ENVIRONMENT      = "DEBUG"
	ENV_TRANSACTIONS_FILE_PATH = "TRANSACTIONS_FILE_PATH"
	ENV_MAX_MEMPOOL_SIZE       = "MAX_MEMPOOL_SIZE"
	PRIORITIZED_TX_FILE_PATH   = "PRIORITIZED_TX_FILE_PATH"
)
